//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    
    public partial class Get_Export_From_ToTime_Event_Payment_Result
    {
        public string Code { get; set; }
        public string Abbott_Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Event_Time { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Area { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<int> Id_Event { get; set; }
        public string HCP_Code { get; set; }
        public string Number_Contract { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<double> Value_Contract { get; set; }
        public Nullable<System.DateTime> PPL_GetContract_Date { get; set; }
        public string Rep_Name { get; set; }
        public string Sup_Name { get; set; }
        public string Description1 { get; set; }
        public Nullable<System.DateTime> PPL_Payment_Date { get; set; }
        public Nullable<double> Payment_Value { get; set; }
        public Nullable<bool> Invoice_Abbott { get; set; }
        public Nullable<System.DateTime> Report_Abbott_Date { get; set; }
        public string Note1 { get; set; }
        public string Details { get; set; }
        public Nullable<double> Honorarium_fee { get; set; }
        public Nullable<double> Air_ticket { get; set; }
        public Nullable<double> Meal_fee { get; set; }
        public Nullable<double> Hotel_fee { get; set; }
        public Nullable<double> Car_rental { get; set; }
        public Nullable<double> Other_fees { get; set; }
        public Nullable<double> Total_costs { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
    }
}
