//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    
    public partial class Get_Service_Cost_byUsr_Result
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> ID_Service_Criteria { get; set; }
        public Nullable<int> ID_Event { get; set; }
        public Nullable<double> Honorarium_fee { get; set; }
        public Nullable<double> Air_ticket { get; set; }
        public Nullable<double> Meal_fee { get; set; }
        public Nullable<double> Hotel_fee { get; set; }
        public Nullable<double> Car_rental { get; set; }
        public Nullable<double> Other_fees { get; set; }
        public Nullable<double> Total_costs { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
    }
}
