//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Info
    {
        public Admin_Info()
        {
            this.Event_Info = new HashSet<Event_Info>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string Region { get; set; }
        public string Area { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
    
        public virtual ICollection<Event_Info> Event_Info { get; set; }
    }
}
