//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HCB_ABBOTTEntities : DbContext
    {
        public HCB_ABBOTTEntities()
            : base("name=HCB_ABBOTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_Info> Admin_Info { get; set; }
        public DbSet<Event_Info> Event_Info { get; set; }
        public DbSet<History_Payment> History_Payment { get; set; }
        public DbSet<UserName> UserNames { get; set; }
        public DbSet<Rate> Rates { get; set; }
        public DbSet<Service_Cost> Service_Cost { get; set; }
        public DbSet<Service_Criteria> Service_Criteria { get; set; }
        public DbSet<User_Create_Rate> User_Create_Rate { get; set; }
        public DbSet<HCP_Info> HCP_Info { get; set; }
    
        public virtual ObjectResult<string> List_Select_Place_Issue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("List_Select_Place_Issue");
        }
    
        public virtual ObjectResult<Get_List_Event_Info_Result> Get_List_Event_Info(Nullable<System.DateTime> event_time, Nullable<System.DateTime> request_date)
        {
            var event_timeParameter = event_time.HasValue ?
                new ObjectParameter("event_time", event_time) :
                new ObjectParameter("event_time", typeof(System.DateTime));
    
            var request_dateParameter = request_date.HasValue ?
                new ObjectParameter("request_date", request_date) :
                new ObjectParameter("request_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Event_Info_Result>("Get_List_Event_Info", event_timeParameter, request_dateParameter);
        }
    
        public virtual ObjectResult<Get_History_Payment_By_Event_Result> Get_History_Payment_By_Event(Nullable<int> id_event)
        {
            var id_eventParameter = id_event.HasValue ?
                new ObjectParameter("id_event", id_event) :
                new ObjectParameter("id_event", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_History_Payment_By_Event_Result>("Get_History_Payment_By_Event", id_eventParameter);
        }
    
        public virtual ObjectResult<Get_List_Chi_Tiet_Dich_Vu_Result> Get_List_Chi_Tiet_Dich_Vu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Chi_Tiet_Dich_Vu_Result>("Get_List_Chi_Tiet_Dich_Vu");
        }
    
        public virtual int Get_Service_Cost_byUsr(string username, string idRateArray, Nullable<int> id_event)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var idRateArrayParameter = idRateArray != null ?
                new ObjectParameter("idRateArray", idRateArray) :
                new ObjectParameter("idRateArray", typeof(string));
    
            var id_eventParameter = id_event.HasValue ?
                new ObjectParameter("id_event", id_event) :
                new ObjectParameter("id_event", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_Service_Cost_byUsr", usernameParameter, idRateArrayParameter, id_eventParameter);
        }
    
        public virtual ObjectResult<Get_Service_User_Create_Rate_Result> Get_Service_User_Create_Rate(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Service_User_Create_Rate_Result>("Get_Service_User_Create_Rate", userParameter);
        }
    
        public virtual int GetRate_byUsr(string username, string idRateArray)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var idRateArrayParameter = idRateArray != null ?
                new ObjectParameter("idRateArray", idRateArray) :
                new ObjectParameter("idRateArray", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRate_byUsr", usernameParameter, idRateArrayParameter);
        }
    
        public virtual ObjectResult<Get_Export_From_ToTime_Event_Payment_Result> Get_Export_From_ToTime_Event_Payment(string fromtime, string totime)
        {
            var fromtimeParameter = fromtime != null ?
                new ObjectParameter("fromtime", fromtime) :
                new ObjectParameter("fromtime", typeof(string));
    
            var totimeParameter = totime != null ?
                new ObjectParameter("totime", totime) :
                new ObjectParameter("totime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Export_From_ToTime_Event_Payment_Result>("Get_Export_From_ToTime_Event_Payment", fromtimeParameter, totimeParameter);
        }
    
        public virtual ObjectResult<Get_Export_From_ToTime_HCP_Info_Result> Get_Export_From_ToTime_HCP_Info(string fromtime, string totime, string place)
        {
            var fromtimeParameter = fromtime != null ?
                new ObjectParameter("fromtime", fromtime) :
                new ObjectParameter("fromtime", typeof(string));
    
            var totimeParameter = totime != null ?
                new ObjectParameter("totime", totime) :
                new ObjectParameter("totime", typeof(string));
    
            var placeParameter = place != null ?
                new ObjectParameter("place", place) :
                new ObjectParameter("place", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Export_From_ToTime_HCP_Info_Result>("Get_Export_From_ToTime_HCP_Info", fromtimeParameter, totimeParameter, placeParameter);
        }
    
        public virtual ObjectResult<Get_List_HCP_Info_Result> Get_List_HCP_Info(string citizen_place)
        {
            var citizen_placeParameter = citizen_place != null ?
                new ObjectParameter("citizen_place", citizen_place) :
                new ObjectParameter("citizen_place", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_HCP_Info_Result>("Get_List_HCP_Info", citizen_placeParameter);
        }
    }
}
