//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Payment
    {
        public int ID { get; set; }
        public Nullable<int> Id_Event { get; set; }
        public string HCP_Code { get; set; }
        public string Number_Contract { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<double> Value_Contract { get; set; }
        public Nullable<System.DateTime> PPL_GetContract_Date { get; set; }
        public string Rep_Name { get; set; }
        public string Sup_Name { get; set; }
        public string Description { get; set; }
        public string Account_Name { get; set; }
        public Nullable<double> Requested_Value { get; set; }
        public Nullable<System.DateTime> Requested_Date { get; set; }
        public Nullable<System.DateTime> PPL_Payment_Date { get; set; }
        public Nullable<double> Payment_Value { get; set; }
        public Nullable<bool> Invoice_Abbott { get; set; }
        public Nullable<System.DateTime> Report_Abbott_Date { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
    
        public virtual Event_Info Event_Info { get; set; }
    }
}
