//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int ID { get; set; }
        public string Rate_Name { get; set; }
        public Nullable<double> Rate_Value { get; set; }
    }
}
