//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    
    public partial class Get_List_Event_Info_Result
    {
        public int ID { get; set; }
        public Nullable<int> Id_Admin_Info { get; set; }
        public string Abbott_Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Event_Time { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Area { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
