//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Create_Rate
    {
        public int ID { get; set; }
        public Nullable<int> Id_User_Name { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<int> Id_rate { get; set; }
    }
}
