//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCB_Port.Models
{
    using System;
    
    public partial class Get_Service_User_Create_Rate_Result
    {
        public Nullable<int> Id_User_Name { get; set; }
        public string UserName { get; set; }
        public int ID_Details { get; set; }
        public int ID_Service_Criteria { get; set; }
        public string Details { get; set; }
        public Nullable<int> ID_Rate { get; set; }
        public string Rate_Name { get; set; }
        public Nullable<int> ID_Event { get; set; }
        public Nullable<double> Honorarium_fee { get; set; }
        public Nullable<double> Air_ticket { get; set; }
        public Nullable<double> Meal_fee { get; set; }
        public Nullable<double> Hotel_fee { get; set; }
        public Nullable<double> Car_rental { get; set; }
        public Nullable<double> Other_fees { get; set; }
        public Nullable<double> Total_costs { get; set; }
    }
}
